# week2-work3

# 【課題１】内積を手計算しよう



A = \left(
\begin{matrix} 
6 & 29 & -20 \\ 
12 & 52 & 38 \\ 
-18 & -51 & -48 
\end{matrix} 
\right)


# 【課題2】1次元配列の内積をfor文で計算しよう

In [101]:
import numpy as np


A = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
B = np.array([[0,2,1],[0,2,-8],[2,9,-1]])

process1 = []

for i in range(0,3):
    process1.append(A[0,i] * B[i,1])
result = sum(process1)
result

29

# 【課題3】多次元配列の内積をfor分で計算しよう

In [102]:
process2 = np.zeros((3,3),int)
for i in range(0,3):
    for j in range(0,3):
        temp = []
        for k in range(0,3):
            temp.append(A[i,k] * B[k,j])
        process2[i,j] = sum(temp)
    print(process2)
process2

[[  6  29 -20]
 [  0   0   0]
 [  0   0   0]]
[[  6  29 -20]
 [ 12  52  38]
 [  0   0   0]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【課題4】内積をnp.dotで計算しよう

In [103]:
np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【課題5】内積ができないときはどうするか

Aの列数とBの行数が一致していないため。

In [104]:
A2 = np.array([[-1,2,3],[4,-5,6]])
B2 = np.array([[-9,8,7],[6,-5,4]])
np.dot(A2,B2.T)

array([[ 46,  -4],
       [-34,  73]])